/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form1;

import java.awt.HeadlessException;
import koneksi.Koneksi;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author windows
 */
public class FormSiswa extends javax.swing.JFrame {
     int idLoginSiswa;
    /**
     * Creates new form FormSiswa
     */
     
private void loadPilihanLomba() {

    try {
         Connection c = Koneksi.configDB();
        Statement s = c.createStatement();

        String sql = "SELECT * FROM lomba";
        ResultSet r = s.executeQuery(sql);

        cmbLomba.removeAllItems();

        while (r.next()) {
            cmbLomba.addItem(
                r.getInt("id") + " - " + r.getString("nama_lomba")
            );
        }

    } catch (SQLException e) {

        JOptionPane.showMessageDialog(
                this,
                "Gagal mengambil data lomba: " + e.getMessage()
        );
    }
}

private void cekStatusSiswa() {

    try {

        Connection c = Koneksi.configDB();
        Statement s = c.createStatement();

        String sql = "SELECT status FROM pendaftaran "
                   + "WHERE user_id=" + idLoginSiswa;

        ResultSet r = s.executeQuery(sql);

        if (r.next()) {

            String status = r.getString("status");

            lblStatus.setText(
                    "*Status anda : " + status + "*"
            );

            btnDaftar.setEnabled(false);

        } else {

            lblStatus.setText(
                    "*Status anda : Belum mendaftar*"
            );

            btnDaftar.setEnabled(true);
        }

    } catch (SQLException e) {

        JOptionPane.showMessageDialog(
                this,
                "Gagal mengecek status: " + e.getMessage()
        );
    }
}
    public FormSiswa(int idUser) {
        initComponents();
        setLocationRelativeTo(null);
        this.idLoginSiswa = idUser;
        loadPilihanLomba();
        cekStatusSiswa();
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbLomba = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnDaftar = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("DASHBOARD SISWA - BI GOT TALENT");

        cmbLomba.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Pilih Mata Lomba");

        btnDaftar.setText("Daftar");
        btnDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarActionPerformed(evt);
            }
        });

        lblStatus.setText("*Status anda : Dokumen dalam tinjauan*");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                                .addComponent(cmbLomba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDaftar)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(85, 85, 85))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbLomba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(btnDaftar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addComponent(lblStatus)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarActionPerformed
          try {

        if (cmbLomba.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(
                    this,
                    "Silakan pilih mata lomba terlebih dahulu!"
            );
            return;
        }

        // Mengambil pilihan dari ComboBox
        String pilihan = cmbLomba.getSelectedItem().toString();

        // Mengambil ID lomba sebelum tanda "-"
        int lombaId = Integer.parseInt(
                pilihan.split(" - ")[0]
        );

        Connection c = Koneksi.configDB();
        Statement s = c.createStatement();

        // Cek apakah siswa sudah pernah mendaftar
        String cek = "SELECT * FROM pendaftaran "
                   + "WHERE user_id=" + idLoginSiswa;

        ResultSet r = s.executeQuery(cek);

        if (r.next()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Kamu sudah melakukan pendaftaran!"
            );

            return;
        }

        // Simpan pendaftaran
        String sql = "INSERT INTO pendaftaran "
                   + "(user_id, lomba_id, status) "
                   + "VALUES ("
                   + idLoginSiswa + ", "
                   + lombaId + ", "
                   + "'Dokumen dalam Tinjauan')";

        s.executeUpdate(sql);

        JOptionPane.showMessageDialog(
                this,
                "Pendaftaran berhasil!"
        );

        lblStatus.setText(
                "*Status anda : Dokumen dalam Tinjauan*"
        );

        btnDaftar.setEnabled(false);

    } catch (HeadlessException | NumberFormatException | SQLException e) {

        JOptionPane.showMessageDialog(
                this,
                "Pendaftaran gagal: " + e.getMessage()
        );
    }
   
    }//GEN-LAST:event_btnDaftarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDaftar;
    private javax.swing.JComboBox<String> cmbLomba;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblStatus;
    // End of variables declaration//GEN-END:variables
}