/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form1;


import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.Koneksi;

/**
 *
 * @author windows
 */
public class FormAdmin extends javax.swing.JFrame {
    DefaultTableModel model;
    /**
     * Creates new form FormAdmin
     */
    public FormAdmin() {
        initComponents();
        setLocationRelativeTo(null);
        loadDataPendaftar();
    }
    
  public void loadDataPendaftar() {

    model = new DefaultTableModel();

    model.addColumn("ID");
    model.addColumn("Nama Siswa");
    model.addColumn("Mata Lomba");
    model.addColumn("Status Tahapan");

    tblPendaftar.setModel(model);

    try {

        Connection c = Koneksi.configDB();
        Statement s = c.createStatement();

        String sql = "SELECT pendaftaran.id, users.username, "
                + "lomba.nama_lomba, pendaftaran.status "
                + "FROM pendaftaran "
                + "JOIN users ON pendaftaran.user_id = users.id "
                + "JOIN lomba ON pendaftaran.lomba_id = lomba.id";

        ResultSet r = s.executeQuery(sql);

        while (r.next()) {

            model.addRow(new Object[]{
                r.getString("id"),
                r.getString("username"),
                r.getString("nama_lomba"),
                r.getString("status")
            });
        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                this,
                "Gagal memuat data: " + e.getMessage()
        );
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtNamaLomba = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnSimpanLomba = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPendaftar = new javax.swing.JTable();
        btnUbahStatus = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("PANEL ADMIN - BI GOT TALENT");

        txtNamaLomba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaLombaActionPerformed(evt);
            }
        });

        jLabel2.setText("Nama Lomba");

        btnSimpanLomba.setText("Simpan");
        btnSimpanLomba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanLombaActionPerformed(evt);
            }
        });

        tblPendaftar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                " ID", "Nama Siswa", "Mata Lomba", "Status Tahapan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPendaftar);

        btnUbahStatus.setText("Ubah");
        btnUbahStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNamaLomba, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSimpanLomba)))))
                .addGap(62, 62, 62))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUbahStatus)
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamaLomba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSimpanLomba))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUbahStatus)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaLombaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaLombaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaLombaActionPerformed

    private void btnSimpanLombaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanLombaActionPerformed
        // TODO add your handling code here:
        
        try {

    Connection c = Koneksi.configDB();
    Statement s = c.createStatement();

    String sql = "INSERT INTO lomba (nama_lomba) VALUES ('"
            + txtNamaLomba.getText() + "')";

    s.executeUpdate(sql);

    JOptionPane.showMessageDialog(
            this,
            "Mata Lomba berhasil ditambahkan!"
    );

    txtNamaLomba.setText("");

} catch (Exception e) {

    JOptionPane.showMessageDialog(
            this,
            "Gagal tambah lomba: " + e.getMessage()
    );
}
    }//GEN-LAST:event_btnSimpanLombaActionPerformed

    private void btnUbahStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahStatusActionPerformed
        // TODO add your handling code here:
        int baris = tblPendaftar.getSelectedRow();

if (baris == -1) {

    JOptionPane.showMessageDialog(
            this,
            "Pilih data siswa di tabel terlebih dahulu!"
    );

    return;
}

String idPendaftaran =
        model.getValueAt(baris, 0).toString();

String statusBaru = JOptionPane.showInputDialog(
        this,
        "Masukkan Status Baru:"
);

if (statusBaru != null
        && !statusBaru.trim().isEmpty()) {

    try {

        Connection c = Koneksi.configDB();
        Statement s = c.createStatement();

        String sql = "UPDATE pendaftaran SET status='"
                + statusBaru
                + "' WHERE id='"
                + idPendaftaran + "'";

        s.executeUpdate(sql);

        JOptionPane.showMessageDialog(
                this,
                "Status berhasil diperbarui!"
        );

        loadDataPendaftar();

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                this,
                "Gagal update status: " + e.getMessage()
        );
    }
}
    }//GEN-LAST:event_btnUbahStatusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimpanLomba;
    private javax.swing.JButton btnUbahStatus;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPendaftar;
    private javax.swing.JTextField txtNamaLomba;
    // End of variables declaration//GEN-END:variables
}
